name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Deploy to gh-pages branch
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          
          mkdir -p /tmp/deploy
          cp -r dist/* /tmp/deploy/
          
          # switch to orphan branch
          git checkout --orphan gh-pages
          
          # remove everything from index and working tree
          git rm -rf .
          
          # copy new build files
          cp -r /tmp/deploy/* .
          
          # commit and push
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -f origin gh-pages

      - name: Configure Custom Domain
        run: |
          curl -X PUT \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pages \
            -d '{"cname":"${{ secrets.CUSTOM_DOMAIN }}"}'
